# Generated by Django 4.1.2 on 2022-10-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='kcal',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='post',
            name='time_to_prepere_in_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.CharField(max_length=50),
        ),
    ]
