# Generated by Django 4.1.2 on 2022-10-22 11:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_level_post_kcal_post_time_to_prepere_in_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.level'),
        ),
        migrations.AlterField(
            model_name='post',
            name='kcal',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_to_prepere_in_minutes',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
