# Generated by Django 4.1.2 on 2022-10-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_level_alter_post_kcal_alter_post_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_name',
            new_name='image',
        ),
    ]
