# Generated by Django 4.1.2 on 2022-11-01 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='level',
        ),
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.profile'),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
