# Generated by Django 4.1.2 on 2022-11-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='kcal',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time_to_prepere_in_minutes',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
